name: zborowskihomepage
description: Szymon Zborowski's homepage.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_icons: ^1.1.0
  animated_text_kit: ^3.1.0
  flutter_custom_clippers: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

fonts:
  - family: Lato
    fonts:
      - asset: fonts/Lato/Lato-Bold.ttf
      - asset: fonts/Lato/Lato-Light.ttf
      - asset: fonts/Lato/Lato-Regular.ttf
